app:
  kafka:
    bootstrap-servers: 10.100.7.21:9092,10.100.7.21:9093,10.100.7.21:9094
    client-id: ${spring.application.name}-${random.uuid}
    acks: all
    retries: 3


spring:
  graphql:
    graphiql:
      # http://localhost:8085/graphiql
      enabled: true
  data:
    mongodb:
      uri: mongodb://root:password123@10.100.7.21:27017/morabehe?authSource=admin  # Use encrypted Environment in !dev

management:
  endpoint:
    web:
      exposure:
        include: "*"

  otlp:
    metrics:
      export:
        url: http://10.100.7.21:4317/v1/metrics
        enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: rest-api
      packages-to-scan: ir.dotin.loan.morabehe.adapters.driving.rest.controller