services:
  postgres:
    image: postgres:18.0-alpine
    container_name: postgres-nova
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-postgres}
      TZ: Asia/Tehran
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  kafka:
#    image: confluentinc/cp-kafka:7.9.4
#    container_name: kafka
#    restart: unless-stopped
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,SASL_PLAINTEXT://0.0.0.0:9094
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9094
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
#      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
#      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf"
#      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
#    volumes:
#      - ./kafka_jaas.conf:/etc/kafka/kafka_jaas.conf:ro
#      - kafka-data:/var/lib/kafka/data
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#      - "9094:9094"
#    networks:
#      - app-network
#    healthcheck:
#      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#
#  kafdrop:
#    image: obsidiandynamics/kafdrop:4.2.0
#    container_name: kafdrop
#    restart: unless-stopped
#    environment:
#      KAFKA_BROKERCONNECT: 127.0.0.1:9092
#      KAFKA_PROPERTIES: |
#        security.protocol=SASL_PLAINTEXT
#        sasl.mechanism=SCRAM-SHA-256
#        sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER}" password="${KAFKA_PASSWORD}";
#      JVM_OPTS: "-Xms32M -Xmx64M"
#      SERVER_SERVLET_CONTEXTPATH: "/"
#    network_mode: host
#    depends_on:
#      kafka:
#        condition: service_healthy
#
#  kafka-rest:
#    image: confluentinc/cp-kafka-rest:8.1.1
#    container_name: kafka-rest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://localhost:9092"
#      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
#      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
#    depends_on:
#      kafka:
#        condition: service_healthy

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"   # JMS
      - "8161:8161"     # Web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - activemq-data:/opt/activemq/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  activemq-data:
#  kafka-data:

networks:
  app-network:
    driver: bridge