<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>trade-loan-container</artifactId>
  <name>Trade Loan :: Container</name>
  <packaging>jar</packaging>

  <properties>
      <start-class>ir.dotin.loan.trade.ir.dotin.loan.trade.config.TradeLoanSpringApplication</start-class>
  </properties>

  <dependencies>
    <dependency>
        <groupId>ir.dotin.platform</groupId>
        <artifactId>platform-starter-all</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-domain</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-application-service</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-application-ports-inbound</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-application-ports-outbound</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-adapters-driving-rest</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-adapters-driven-persistence</artifactId>
    </dependency>
    <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <exclusions>
            <exclusion>
                <groupId>org.checkerframework</groupId>
                <artifactId>checker-qual</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
  </dependencies>
</project>
