<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ir.dotin.platform</groupId>
        <artifactId>platform-parent</artifactId>
        <version>2026.4.12-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan</artifactId>
    <name>Trade Loan</name>
    <packaging>pom</packaging>
    <version>${revision}</version>

    <scm>
        <connection>scm:git:https://bitbucket.dotin.ir/scm/core/trade-loan.git</connection>
        <developerConnection>scm:git:https://bitbucket.dotin.ir/scm/core/trade-loan.git</developerConnection>
        <url>https://bitbucket.dotin.ir/projects/core/repos/trade-loan</url>
    </scm>

    <modules>
        <module>core</module>
        <module>adapters</module>
        <module>container</module>
        <module>architecture-tests</module>
        <!--  mvn -pl documents/c4/java process-classes-->
        <module>documents/c4/java</module>
    </modules>

    <properties>
        <loan.base-loan.version>2026.4.2-SNAPSHOT</loan.base-loan.version>
        <loan.trade-loan.version>${project.version}</loan.trade-loan.version>
        <sonar.projectVersion>${project.version}</sonar.projectVersion>
        <platform.accounting.document.version>2026.4.1-SNAPSHOT</platform.accounting.document.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-pool2</artifactId>
            </dependency>
            <!--region base-loan -->
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>base-loan-core-domain</artifactId>
                <version>${loan.base-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <!--endregion-->
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-core-domain</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-core-application-ports-outbound</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-core-application-ports-inbound</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-core-application-service</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-core-application-query</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driven-persistence</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driving-rest</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driving-contract</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driving-messaging-kafka</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driving-messaging-activemq</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driven-fcb-client</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>ir.dotin.loan</groupId>
                <artifactId>trade-loan-adapters-driven-fcb-messaging</artifactId>
                <version>${loan.trade-loan.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>ir.dotin.platform</groupId>
                <artifactId>accounting-document-api</artifactId>
                <version>${platform.accounting.document.version}</version>
            </dependency>
            <dependency>
                <groupId>ir.dotin.platform</groupId>
                <artifactId>accounting-document-core</artifactId>
                <version>${platform.accounting.document.version}</version>
            </dependency>
            <dependency>
                <groupId>ir.dotin.platform</groupId>
                <artifactId>accounting-document-spring-boot-starter</artifactId>
                <version>${platform.accounting.document.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
