sonar.projectKey=ir.dotin.loan:morabehe-loan
sonar.projectName=MorabeheLoan
sonar.projectVersion=0.0.2-SNAPSHOT
sonar.sourceEncoding=UTF-8
sonar.modules=core,adapters,container

# Module: core adapters container
