<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan-adapters</artifactId>
    <version>2025.12.37-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>trade-loan-adapters-driving</artifactId>
  <name>Trade Loan :: Adapters :: Driving</name>
  <packaging>pom</packaging>

  <modules>
    <module>rest</module>
    <module>messaging</module>
  </modules>

  <dependencies>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-application-ports-inbound</artifactId>
    </dependency>

  </dependencies>

</project>
