bind 0.0.0.0
protected-mode yes
port 6379
appendonly yes
appendfsync everysec
maxmemory-policy allkeys-lru
tcp-keepalive 60
replica-read-only yes
replica-announce-ip ${ANNOUNCE_IP}
replica-announce-port 6379
