<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan-core-application</artifactId>
    <version>2025.12.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>trade-loan-core-application-service</artifactId>
  <name>Trade Loan :: Core :: Application :: Service</name>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-application-ports-outbound</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-application-ports-inbound</artifactId>
    </dependency>

    <dependency>
        <groupId>ir.dotin.platform</groupId>
        <artifactId>platform-saga-api</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-tx</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>


</project>
