<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ir.dotin.loan</groupId>
        <artifactId>trade-loan</artifactId>
        <version>2025.12.30-SNAPSHOT</version>
    </parent>

    <artifactId>trade-architecture-tests</artifactId>
    <name>Trade Loan :: Architecture Tests</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>ir.dotin.platform</groupId>
            <artifactId>platform-test-archunit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.dotin.loan</groupId>
            <artifactId>trade-loan-core-domain</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.dotin.loan</groupId>
            <artifactId>trade-loan-core-application-service</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.dotin.loan</groupId>
            <artifactId>trade-loan-core-application-ports-inbound</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.dotin.loan</groupId>
            <artifactId>trade-loan-core-application-ports-outbound</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.dotin.loan</groupId>
            <artifactId>trade-loan-adapters-driving-rest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.dotin.loan</groupId>
            <artifactId>trade-loan-adapters-driven-persistence</artifactId>
            <scope>test</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>ir.dotin.loan</groupId>-->
<!--            <artifactId>trade-loan-adapters-driven-messaging</artifactId>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->
    </dependencies>

</project>