apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - sealed-secret.yml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: trade-loan-service
    spec:
      template:
        spec:
          containers:
            - name: trade-loan-service
              env:
                - name: LOG_LEVEL_WEB
                  value: "DEBUG"
                - name: LOG_LEVEL_APP
                  value: "DEBUG"
                - name: SHOW_SQL
                  value: "true"