apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-loan-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: trade-loan-service
          env:
            - name: HIBERNATE_DDL_AUTO
              value: "validate"
            - name: LOG_LEVEL_WEB
              value: "INFO"
            - name: LOG_LEVEL_APP
              value: "INFO"
            - name: SHOW_SQL
              value: "false"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"