# Create with: kubeseal -f secret.yml -w sealed-secret.yml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trade-loan-service-secrets
  namespace: default
spec:
  encryptedData:
    spring.datasource.url: AgA...
    spring.datasource.username: AgB...
    spring.datasource.password: AgC...
    platform.messaging.encryption.password: AgD...