<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan</artifactId>
    <version>2025.12.14-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>trade-loan-core</artifactId>
  <name>Trade Loan :: Core</name>
  <packaging>pom</packaging>

  <modules>
    <module>domain</module>
    <module>application</module>
  </modules>

</project>
