server:
  port: 8085
# region Spring config
spring:
  data:
    mongodb:
      uri: mongodb://root:password123@10.20.151.144:27017/morabehe?authSource=admin
  application:
    name: Morabehe
# region Camel config
camel:
  servlet:
    mapping:
      context-path: /api/*
      enabled: true
  rest:
    host: 127.0.0.1
    port: 8085
    api-context-path: /api-doc
    api-host: 127.0.0.1
    api-property:
      api.title: Morabehe Rest API.
      api.version: 0.0.1-SNAPSHOT
    api-context-route-id: doc-api
    component: servlet
    enable-cors: false
    binding-mode: auto
    context-path: /api
#  region log config
logging:
  level:
    ir.dotin.loan: DEBUG

