<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan-core</artifactId>
    <version>2025.12.18-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <properties>
    <org.mapstruct.version>1.6.3</org.mapstruct.version>
  </properties>

  <artifactId>trade-loan-core-application</artifactId>
  <name>Trade Loan :: Core :: Application</name>
  <packaging>pom</packaging>

  <modules>
    <module>ports</module>
    <module>service</module>
    <module>query</module>
  </modules>

  <dependencies>
    <dependency>
      <groupId>ir.dotin.platform</groupId>
      <artifactId>platform-dispatcher-api</artifactId>
    </dependency>
    <dependency>
      <groupId>ir.dotin.loan</groupId>
      <artifactId>trade-loan-core-domain</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct</artifactId>
    </dependency>
  </dependencies>

</project>
