package ir.dotin.loan.trade.core.domain.loanfacility.event;

public enum TradeLoanFacilityEventType {
    CREATED,
    APPROVAL_SUBMITTED,
    APPROVED,
    REJECTED,
    LUMP_SUM_DISBURSED,
    CONTRACT_ISSUED,
    CONTRACT_ISSUANCE_REVERTED,
    COLLATERAL_ADDED,
    IRREGULAR_TRANCHE_DISBURSED,
    DISBURSEMENT_FAILED,
    CLOSED_PAID_OFF,
    CLOSED_DEFAULTED,
    FULLY_DISBURSED,
    CANCELLED,
    ORIGINATION_REVERTED,
    APPROVAL_SUBMISSION_REVERTED,
    APPROVAL_REVERTED,
    DISBURSEMENT_REVERTED,
    IRREGULAR_TRANCHE_DISBURSEMENT_REVERTED,
    ADD_COLLATERAL_REVERTED,
    CLOSED_PAID_OFF_REVERTED,
    RESTRUCTURING;

    private static final String PREFIX = "TRADE_LOAN_FACILITY_";

    public String getFullType() {
        return PREFIX + name();
    }
}
