<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ir.dotin.loan</groupId>
    <artifactId>trade-loan-adapters-driving</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>trade-loan-adapters-driving-contract</artifactId>
  <name>Trade Loan :: Adapters :: Driving :: Contract</name>
  <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>ir.dotin.platform.pangaea</groupId>
            <artifactId>messaging-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ir.dotin.platform</groupId>
            <artifactId>expression-kit-service</artifactId>
        </dependency>
        <dependency>
            <groupId>net.time4j</groupId>
            <artifactId>time4j-base</artifactId>
            <version>5.9.4</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
    </dependencies>
</project>
