@startuml
set separator none
title Trade Loan Service - Trade Loan Application - Components

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam hexagon<<TradeLoanService.TradeLoanApplication.InstallmentScheduleOutboxHandler>> {
  BackgroundColor #66bb6a
  FontColor #000000
  BorderColor #47824a
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.InstallmentScheduleRepositoryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.IssueFacilityContractSaga>> {
  BackgroundColor #ab47bc
  FontColor #ffffff
  BorderColor #773183
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.JpaFacilityQueryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.JpaTradeInstallmentScheduleQueryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.JpaTradeLoanArrangementQueryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.JpaTradeLoanTypeQueryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.LumpSumDisbursementSaga>> {
  BackgroundColor #ab47bc
  FontColor #ffffff
  BorderColor #773183
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanApplication>> {
  BackgroundColor #ff9800
  FontColor #000000
  BorderColor #b26a00
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanArrangement>> {
  BackgroundColor #ff9800
  FontColor #000000
  BorderColor #b26a00
  shadowing false
}
skinparam hexagon<<TradeLoanService.TradeLoanApplication.TradeLoanArrangementOutboxHandler>> {
  BackgroundColor #66bb6a
  FontColor #000000
  BorderColor #47824a
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.TradeLoanArrangementRepositoryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanFacility>> {
  BackgroundColor #ff9800
  FontColor #000000
  BorderColor #b26a00
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanFacilityEventFactory>> {
  BackgroundColor #ffb74d
  FontColor #000000
  BorderColor #b28035
  shadowing false
}
skinparam hexagon<<TradeLoanService.TradeLoanApplication.TradeLoanFacilityOutboxHandler>> {
  BackgroundColor #66bb6a
  FontColor #000000
  BorderColor #47824a
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.TradeLoanFacilityRepositoryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanFacilityService>> {
  BackgroundColor #29b6f6
  FontColor #ffffff
  BorderColor #1c7fac
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanFacilityValidationService>> {
  BackgroundColor #29b6f6
  FontColor #ffffff
  BorderColor #1c7fac
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanType>> {
  BackgroundColor #ff9800
  FontColor #000000
  BorderColor #b26a00
  shadowing false
}
skinparam hexagon<<TradeLoanService.TradeLoanApplication.TradeLoanTypeOutboxHandler>> {
  BackgroundColor #66bb6a
  FontColor #000000
  BorderColor #47824a
  shadowing false
}
skinparam database<<TradeLoanService.TradeLoanApplication.TradeLoanTypeRepositoryAdapter>> {
  BackgroundColor #5c6bc0
  FontColor #ffffff
  BorderColor #404a86
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeLoanTypeValidationService>> {
  BackgroundColor #29b6f6
  FontColor #ffffff
  BorderColor #1c7fac
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeRepaymentSchedulingService>> {
  BackgroundColor #29b6f6
  FontColor #ffffff
  BorderColor #1c7fac
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeSanctionValidationService>> {
  BackgroundColor #29b6f6
  FontColor #ffffff
  BorderColor #1c7fac
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.TradeSanctionedLoan>> {
  BackgroundColor #ff9800
  FontColor #000000
  BorderColor #b26a00
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Trade Loan Application\n<size:10>[Container: Java 25, Spring Boot 4]</size>" <<TradeLoanService.TradeLoanApplication>> {
  rectangle "==IssueFacilityContractSaga\n<size:10>[Component: Saga Orchestrator]</size>\n\nOrchestrates issue facility contract" <<TradeLoanService.TradeLoanApplication.IssueFacilityContractSaga>> as TradeLoanService.TradeLoanApplication.IssueFacilityContractSaga
  rectangle "==LumpSumDisbursementSaga\n<size:10>[Component: Saga Orchestrator]</size>\n\nOrchestrates lump sum disbursement" <<TradeLoanService.TradeLoanApplication.LumpSumDisbursementSaga>> as TradeLoanService.TradeLoanApplication.LumpSumDisbursementSaga
  rectangle "==TradeLoanArrangement\n<size:10>[Component: DDD Aggregate Root]</size>\n\ntrade loan arrangement aggregate" <<TradeLoanService.TradeLoanApplication.TradeLoanArrangement>> as TradeLoanService.TradeLoanApplication.TradeLoanArrangement
  rectangle "==TradeLoanApplication\n<size:10>[Component: DDD Aggregate Root]</size>\n\ntrade loan application aggregate" <<TradeLoanService.TradeLoanApplication.TradeLoanApplication>> as TradeLoanService.TradeLoanApplication.TradeLoanApplication
  rectangle "==TradeLoanFacility\n<size:10>[Component: DDD Aggregate Root]</size>\n\ntrade loan facility aggregate" <<TradeLoanService.TradeLoanApplication.TradeLoanFacility>> as TradeLoanService.TradeLoanApplication.TradeLoanFacility
  rectangle "==TradeLoanFacilityEventFactory\n<size:10>[Component: DDD Entity]</size>\n\ntrade loan facility event factory entity" <<TradeLoanService.TradeLoanApplication.TradeLoanFacilityEventFactory>> as TradeLoanService.TradeLoanApplication.TradeLoanFacilityEventFactory
  rectangle "==TradeSanctionedLoan\n<size:10>[Component: DDD Aggregate Root]</size>\n\ntrade sanctioned loan aggregate" <<TradeLoanService.TradeLoanApplication.TradeSanctionedLoan>> as TradeLoanService.TradeLoanApplication.TradeSanctionedLoan
  rectangle "==TradeLoanType\n<size:10>[Component: DDD Aggregate Root]</size>\n\ntrade loan type aggregate" <<TradeLoanService.TradeLoanApplication.TradeLoanType>> as TradeLoanService.TradeLoanApplication.TradeLoanType
  rectangle "==TradeRepaymentSchedulingService\n<size:10>[Component: Domain Service]</size>\n\ntrade repayment scheduling service domain service" <<TradeLoanService.TradeLoanApplication.TradeRepaymentSchedulingService>> as TradeLoanService.TradeLoanApplication.TradeRepaymentSchedulingService
  rectangle "==TradeLoanFacilityService\n<size:10>[Component: Domain Service]</size>\n\ntrade loan facility service domain service" <<TradeLoanService.TradeLoanApplication.TradeLoanFacilityService>> as TradeLoanService.TradeLoanApplication.TradeLoanFacilityService
  rectangle "==TradeLoanFacilityValidationService\n<size:10>[Component: Domain Service]</size>\n\ntrade loan facility validation service domain service" <<TradeLoanService.TradeLoanApplication.TradeLoanFacilityValidationService>> as TradeLoanService.TradeLoanApplication.TradeLoanFacilityValidationService
  rectangle "==TradeSanctionValidationService\n<size:10>[Component: Domain Service]</size>\n\ntrade sanction validation service domain service" <<TradeLoanService.TradeLoanApplication.TradeSanctionValidationService>> as TradeLoanService.TradeLoanApplication.TradeSanctionValidationService
  rectangle "==TradeLoanTypeValidationService\n<size:10>[Component: Domain Service]</size>\n\ntrade loan type validation service domain service" <<TradeLoanService.TradeLoanApplication.TradeLoanTypeValidationService>> as TradeLoanService.TradeLoanApplication.TradeLoanTypeValidationService
  database "==InstallmentScheduleRepositoryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nInstallmentSchedule persistence adapter" <<TradeLoanService.TradeLoanApplication.InstallmentScheduleRepositoryAdapter>> as TradeLoanService.TradeLoanApplication.InstallmentScheduleRepositoryAdapter
  database "==TradeLoanArrangementRepositoryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nTradeLoanArrangement persistence adapter" <<TradeLoanService.TradeLoanApplication.TradeLoanArrangementRepositoryAdapter>> as TradeLoanService.TradeLoanApplication.TradeLoanArrangementRepositoryAdapter
  database "==TradeLoanFacilityRepositoryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nTradeLoanFacility persistence adapter" <<TradeLoanService.TradeLoanApplication.TradeLoanFacilityRepositoryAdapter>> as TradeLoanService.TradeLoanApplication.TradeLoanFacilityRepositoryAdapter
  database "==TradeLoanTypeRepositoryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nTradeLoanType persistence adapter" <<TradeLoanService.TradeLoanApplication.TradeLoanTypeRepositoryAdapter>> as TradeLoanService.TradeLoanApplication.TradeLoanTypeRepositoryAdapter
  database "==JpaTradeInstallmentScheduleQueryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nTradeInstallmentSchedule query adapter" <<TradeLoanService.TradeLoanApplication.JpaTradeInstallmentScheduleQueryAdapter>> as TradeLoanService.TradeLoanApplication.JpaTradeInstallmentScheduleQueryAdapter
  database "==JpaTradeLoanArrangementQueryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nTradeLoanArrangement query adapter" <<TradeLoanService.TradeLoanApplication.JpaTradeLoanArrangementQueryAdapter>> as TradeLoanService.TradeLoanApplication.JpaTradeLoanArrangementQueryAdapter
  database "==JpaFacilityQueryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nFacility query adapter" <<TradeLoanService.TradeLoanApplication.JpaFacilityQueryAdapter>> as TradeLoanService.TradeLoanApplication.JpaFacilityQueryAdapter
  database "==JpaTradeLoanTypeQueryAdapter\n<size:10>[Component: Spring Data JPA]</size>\n\nTradeLoanType query adapter" <<TradeLoanService.TradeLoanApplication.JpaTradeLoanTypeQueryAdapter>> as TradeLoanService.TradeLoanApplication.JpaTradeLoanTypeQueryAdapter
  hexagon "==InstallmentScheduleOutboxHandler\n<size:10>[Component: Outbox Pattern]</size>\n\nInstallmentSchedule outbox handler" <<TradeLoanService.TradeLoanApplication.InstallmentScheduleOutboxHandler>> as TradeLoanService.TradeLoanApplication.InstallmentScheduleOutboxHandler
  hexagon "==TradeLoanArrangementOutboxHandler\n<size:10>[Component: Outbox Pattern]</size>\n\nTradeLoanArrangement outbox handler" <<TradeLoanService.TradeLoanApplication.TradeLoanArrangementOutboxHandler>> as TradeLoanService.TradeLoanApplication.TradeLoanArrangementOutboxHandler
  hexagon "==TradeLoanFacilityOutboxHandler\n<size:10>[Component: Outbox Pattern]</size>\n\nTradeLoanFacility outbox handler" <<TradeLoanService.TradeLoanApplication.TradeLoanFacilityOutboxHandler>> as TradeLoanService.TradeLoanApplication.TradeLoanFacilityOutboxHandler
  hexagon "==TradeLoanTypeOutboxHandler\n<size:10>[Component: Outbox Pattern]</size>\n\nTradeLoanType outbox handler" <<TradeLoanService.TradeLoanApplication.TradeLoanTypeOutboxHandler>> as TradeLoanService.TradeLoanApplication.TradeLoanTypeOutboxHandler
}

@enduml