@startuml
set separator none
title Trade Loan Service - Trade Loan Application - Components

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<TradeLoanService.TradeLoanApplication.AddFacilityCollateralController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.ApproveFacilityController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.DefineLoanArrangementController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.DefineLoanTypeController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.DevAuthCallbackController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.FacilityQueryController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.FullLoanFacilityLifecycleController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.InstallmentScheduleQueryController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.IssueFacilityContractController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.LoanArrangementQueryController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.LoanTypeQueryController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.LumpSumDisbursementController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.OpenFacilityCaseController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.RegularDisbursementController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.RejectFacilityController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalController>> {
  BackgroundColor #7cb342
  FontColor #ffffff
  BorderColor #567d2e
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Trade Loan Application\n<size:10>[Container: Java 25, Spring Boot 4]</size>" <<TradeLoanService.TradeLoanApplication>> {
  rectangle "==DevAuthCallbackController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /api/{version}/dev/auth" <<TradeLoanService.TradeLoanApplication.DevAuthCallbackController>> as TradeLoanService.TradeLoanApplication.DevAuthCallbackController
  rectangle "==AddFacilityCollateralController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/collaterals" <<TradeLoanService.TradeLoanApplication.AddFacilityCollateralController>> as TradeLoanService.TradeLoanApplication.AddFacilityCollateralController
  rectangle "==ApproveFacilityController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/approve" <<TradeLoanService.TradeLoanApplication.ApproveFacilityController>> as TradeLoanService.TradeLoanApplication.ApproveFacilityController
  rectangle "==CloseFacilityDefaultedController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/close-defaulted" <<TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedController>> as TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedController
  rectangle "==CloseFacilityPaidOffController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/close-paid-off" <<TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffController>> as TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffController
  rectangle "==DefineLoanArrangementController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-arrangements" <<TradeLoanService.TradeLoanApplication.DefineLoanArrangementController>> as TradeLoanService.TradeLoanApplication.DefineLoanArrangementController
  rectangle "==DefineLoanTypeController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-types" <<TradeLoanService.TradeLoanApplication.DefineLoanTypeController>> as TradeLoanService.TradeLoanApplication.DefineLoanTypeController
  rectangle "==FullLoanFacilityLifecycleController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/full-lifecycle" <<TradeLoanService.TradeLoanApplication.FullLoanFacilityLifecycleController>> as TradeLoanService.TradeLoanApplication.FullLoanFacilityLifecycleController
  rectangle "==IrregularProgressiveDisbursementController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/disburse/progressive-irregular" <<TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementController>> as TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementController
  rectangle "==IssueFacilityContractController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/issue-contract" <<TradeLoanService.TradeLoanApplication.IssueFacilityContractController>> as TradeLoanService.TradeLoanApplication.IssueFacilityContractController
  rectangle "==LumpSumDisbursementController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/disburse/lump-sum" <<TradeLoanService.TradeLoanApplication.LumpSumDisbursementController>> as TradeLoanService.TradeLoanApplication.LumpSumDisbursementController
  rectangle "==OpenFacilityCaseController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities" <<TradeLoanService.TradeLoanApplication.OpenFacilityCaseController>> as TradeLoanService.TradeLoanApplication.OpenFacilityCaseController
  rectangle "==RegularDisbursementController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /api/{version}/facilities/{facilityId}/disburse/regular" <<TradeLoanService.TradeLoanApplication.RegularDisbursementController>> as TradeLoanService.TradeLoanApplication.RegularDisbursementController
  rectangle "==RejectFacilityController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/reject" <<TradeLoanService.TradeLoanApplication.RejectFacilityController>> as TradeLoanService.TradeLoanApplication.RejectFacilityController
  rectangle "==SubmitFacilityForApprovalController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities/{facilityId}/submit-for-approval" <<TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalController>> as TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalController
  rectangle "==InstallmentScheduleQueryController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/installment-schedules" <<TradeLoanService.TradeLoanApplication.InstallmentScheduleQueryController>> as TradeLoanService.TradeLoanApplication.InstallmentScheduleQueryController
  rectangle "==LoanArrangementQueryController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-arrangements" <<TradeLoanService.TradeLoanApplication.LoanArrangementQueryController>> as TradeLoanService.TradeLoanApplication.LoanArrangementQueryController
  rectangle "==FacilityQueryController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-facilities" <<TradeLoanService.TradeLoanApplication.FacilityQueryController>> as TradeLoanService.TradeLoanApplication.FacilityQueryController
  rectangle "==LoanTypeQueryController\n<size:10>[Component: Spring REST Controller]</size>\n\nREST API: /v{version}/loan-types" <<TradeLoanService.TradeLoanApplication.LoanTypeQueryController>> as TradeLoanService.TradeLoanApplication.LoanTypeQueryController
}

@enduml