@startuml
set separator none
title Trade Loan Service - Trade Loan Application - Components

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<TradeLoanService.TradeLoanApplication.AddFacilityCollateralCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.ApproveFacilityCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CancelFacilityCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CollectInstallmentCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateApprovalCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateApprovalSubmissionCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateCollateralCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateCollectInstallmentCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateContractIssuanceCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateIrregularDisbursementCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateLumpSumDisbursementCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.CompensateOriginationCommandHandler>> {
  BackgroundColor #ef5350
  FontColor #ffffff
  BorderColor #a73a38
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.DefineLoanTypeCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.DefineTradeLoanArrangementCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.FindAllLoanArrangementsQueryHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.FullLifecycleRevertCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.FullLoanFacilityLifecycleCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.GetInstallmentScheduleByIdQueryHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.GetLoanArrangementByIdQueryHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.IssueFacilityContractCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.LoanTypeArrangementFilterQueryHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.LumpSumDisbursementCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.OriginateLoanFacilityCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.PlanEqualInstallmentScheduleCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.RegularDisbursementCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.RejectFacilityCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalCommandHandler>> {
  BackgroundColor #42a5f5
  FontColor #ffffff
  BorderColor #2e73ab
  shadowing false
}
skinparam rectangle<<TradeLoanService.TradeLoanApplication>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Trade Loan Application\n<size:10>[Container: Java 25, Spring Boot 4]</size>" <<TradeLoanService.TradeLoanApplication>> {
  rectangle "==GetLoanArrangementByIdQueryHandler\n<size:10>[Component: Query Handler]</size>\n\nHandles get loan arrangement by id queries" <<TradeLoanService.TradeLoanApplication.GetLoanArrangementByIdQueryHandler>> as TradeLoanService.TradeLoanApplication.GetLoanArrangementByIdQueryHandler
  rectangle "==LoanTypeArrangementFilterQueryHandler\n<size:10>[Component: Query Handler]</size>\n\nHandles loan type arrangement filter queries" <<TradeLoanService.TradeLoanApplication.LoanTypeArrangementFilterQueryHandler>> as TradeLoanService.TradeLoanApplication.LoanTypeArrangementFilterQueryHandler
  rectangle "==AddFacilityCollateralCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles add facility collateral" <<TradeLoanService.TradeLoanApplication.AddFacilityCollateralCommandHandler>> as TradeLoanService.TradeLoanApplication.AddFacilityCollateralCommandHandler
  rectangle "==CompensateCollateralCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate collateral" <<TradeLoanService.TradeLoanApplication.CompensateCollateralCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateCollateralCommandHandler
  rectangle "==ApproveFacilityCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles approve facility" <<TradeLoanService.TradeLoanApplication.ApproveFacilityCommandHandler>> as TradeLoanService.TradeLoanApplication.ApproveFacilityCommandHandler
  rectangle "==CompensateApprovalCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate approval" <<TradeLoanService.TradeLoanApplication.CompensateApprovalCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateApprovalCommandHandler
  rectangle "==CancelFacilityCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles cancel facility" <<TradeLoanService.TradeLoanApplication.CancelFacilityCommandHandler>> as TradeLoanService.TradeLoanApplication.CancelFacilityCommandHandler
  rectangle "==CloseFacilityDefaultedCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles close facility defaulted" <<TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedCommandHandler>> as TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedCommandHandler
  rectangle "==CloseFacilityPaidOffCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles close facility paid off" <<TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffCommandHandler>> as TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffCommandHandler
  rectangle "==CollectInstallmentCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles collect installment" <<TradeLoanService.TradeLoanApplication.CollectInstallmentCommandHandler>> as TradeLoanService.TradeLoanApplication.CollectInstallmentCommandHandler
  rectangle "==CompensateCollectInstallmentCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate collect installment" <<TradeLoanService.TradeLoanApplication.CompensateCollectInstallmentCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateCollectInstallmentCommandHandler
  rectangle "==DefineTradeLoanArrangementCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles define trade loan arrangement" <<TradeLoanService.TradeLoanApplication.DefineTradeLoanArrangementCommandHandler>> as TradeLoanService.TradeLoanApplication.DefineTradeLoanArrangementCommandHandler
  rectangle "==DefineLoanTypeCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles define loan type" <<TradeLoanService.TradeLoanApplication.DefineLoanTypeCommandHandler>> as TradeLoanService.TradeLoanApplication.DefineLoanTypeCommandHandler
  rectangle "==FullLoanFacilityLifecycleCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles full loan facility lifecycle" <<TradeLoanService.TradeLoanApplication.FullLoanFacilityLifecycleCommandHandler>> as TradeLoanService.TradeLoanApplication.FullLoanFacilityLifecycleCommandHandler
  rectangle "==FullLifecycleRevertCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles full lifecycle revert" <<TradeLoanService.TradeLoanApplication.FullLifecycleRevertCommandHandler>> as TradeLoanService.TradeLoanApplication.FullLifecycleRevertCommandHandler
  rectangle "==IrregularProgressiveDisbursementCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles irregular progressive disbursement" <<TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementCommandHandler>> as TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementCommandHandler
  rectangle "==CompensateIrregularDisbursementCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate irregular disbursement" <<TradeLoanService.TradeLoanApplication.CompensateIrregularDisbursementCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateIrregularDisbursementCommandHandler
  rectangle "==IssueFacilityContractCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles issue facility contract" <<TradeLoanService.TradeLoanApplication.IssueFacilityContractCommandHandler>> as TradeLoanService.TradeLoanApplication.IssueFacilityContractCommandHandler
  rectangle "==CompensateContractIssuanceCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate contract issuance" <<TradeLoanService.TradeLoanApplication.CompensateContractIssuanceCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateContractIssuanceCommandHandler
  rectangle "==LumpSumDisbursementCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles lump sum disbursement" <<TradeLoanService.TradeLoanApplication.LumpSumDisbursementCommandHandler>> as TradeLoanService.TradeLoanApplication.LumpSumDisbursementCommandHandler
  rectangle "==CompensateLumpSumDisbursementCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate lump sum disbursement" <<TradeLoanService.TradeLoanApplication.CompensateLumpSumDisbursementCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateLumpSumDisbursementCommandHandler
  rectangle "==OriginateLoanFacilityCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles originate loan facility" <<TradeLoanService.TradeLoanApplication.OriginateLoanFacilityCommandHandler>> as TradeLoanService.TradeLoanApplication.OriginateLoanFacilityCommandHandler
  rectangle "==CompensateOriginationCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate origination" <<TradeLoanService.TradeLoanApplication.CompensateOriginationCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateOriginationCommandHandler
  rectangle "==PlanEqualInstallmentScheduleCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles plan equal installment schedule" <<TradeLoanService.TradeLoanApplication.PlanEqualInstallmentScheduleCommandHandler>> as TradeLoanService.TradeLoanApplication.PlanEqualInstallmentScheduleCommandHandler
  rectangle "==RegularDisbursementCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles regular disbursement" <<TradeLoanService.TradeLoanApplication.RegularDisbursementCommandHandler>> as TradeLoanService.TradeLoanApplication.RegularDisbursementCommandHandler
  rectangle "==RejectFacilityCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles reject facility" <<TradeLoanService.TradeLoanApplication.RejectFacilityCommandHandler>> as TradeLoanService.TradeLoanApplication.RejectFacilityCommandHandler
  rectangle "==SubmitFacilityForApprovalCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles submit facility for approval" <<TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalCommandHandler>> as TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalCommandHandler
  rectangle "==CompensateApprovalSubmissionCommandHandler\n<size:10>[Component: Command Handler]</size>\n\nHandles compensate approval submission" <<TradeLoanService.TradeLoanApplication.CompensateApprovalSubmissionCommandHandler>> as TradeLoanService.TradeLoanApplication.CompensateApprovalSubmissionCommandHandler
  rectangle "==GetInstallmentScheduleByIdQueryHandler\n<size:10>[Component: Query Handler]</size>\n\nHandles get installment schedule by id queries" <<TradeLoanService.TradeLoanApplication.GetInstallmentScheduleByIdQueryHandler>> as TradeLoanService.TradeLoanApplication.GetInstallmentScheduleByIdQueryHandler
  rectangle "==FindAllLoanArrangementsQueryHandler\n<size:10>[Component: Query Handler]</size>\n\nHandles find all loan arrangements queries" <<TradeLoanService.TradeLoanApplication.FindAllLoanArrangementsQueryHandler>> as TradeLoanService.TradeLoanApplication.FindAllLoanArrangementsQueryHandler
}

@enduml