@startuml
set separator none
title Trade Loan Service - Trade Loan Application - Components

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype


@enduml