@startuml
title <size:24>Component View: Trade Loan Service - Trade Loan Application</size>\n<size:24>Workflow orchestration flow</size>

set separator none
left to right direction
skinparam ranksep 80
skinparam nodesep 30
hide stereotype

<style>
  root {
    BackgroundColor: #ffffff;
    FontColor: #444444;
  }
  // Element,Component,Controller
  .Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg== {
    BackgroundColor: #7cb342;
    LineColor: #567d2e;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Element,Component,Handler
  .Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg== {
    BackgroundColor: #42a5f5;
    LineColor: #2e73ab;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Element,Component,Handler,Compensation
  .Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcixDb21wZW5zYXRpb24= {
    BackgroundColor: #ef5350;
    LineColor: #a73a38;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Trade Loan Application
  .Boundary-VHJhZGUgTG9hbiBBcHBsaWNhdGlvbg== {
    BackgroundColor: #ffffff;
    LineColor: #2e6295;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
  }
  // Trade Loan Service
  .Boundary-VHJhZGUgTG9hbiBTZXJ2aWNl {
    BackgroundColor: #ffffff;
    LineColor: #0b4884;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
  }
</style>

rectangle "Trade Loan Service\n<size:16>[Software System]</size>" <<Boundary-VHJhZGUgTG9hbiBTZXJ2aWNl>> {
  rectangle "Trade Loan Application\n<size:16>[Container: Java 25, Spring Boot 4]</size>" <<Boundary-VHJhZGUgTG9hbiBBcHBsaWNhdGlvbg==>> {
    rectangle "==Reconciliation By Application Number Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.ReconciliationByApplicationNumberController
    rectangle "==Dev Auth Callback Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.DevAuthCallbackController
    rectangle "==Loan Arrangement Query Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.LoanArrangementQueryController
    rectangle "==Installment Schedule Query Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.InstallmentScheduleQueryController
    rectangle "==Loan Type Query Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.LoanTypeQueryController
    rectangle "==Facility Query Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.FacilityQueryController
    rectangle "==Approve Facility Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.ApproveFacilityController
    rectangle "==Issue Facility Contract Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.IssueFacilityContractController
    rectangle "==Add Facility Collateral Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.AddFacilityCollateralController
    rectangle "==Define Loan Arrangement Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.DefineLoanArrangementController
    rectangle "==Lump Sum Disbursement Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.LumpSumDisbursementController
    rectangle "==Define Loan Type Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.DefineLoanTypeController
    rectangle "==Submit Facility For Approval Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalController
    rectangle "==Reject Facility Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.RejectFacilityController
    rectangle "==Open Facility Case Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.OpenFacilityCaseController
    rectangle "==Irregular Progressive Disbursement Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementController
    rectangle "==Close Facility Defaulted Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.CloseFacilityDefaultedController
    rectangle "==Close Facility Paid Off Controller\n<size:16>[Component: Spring MVC Controller]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsQ29udHJvbGxlcg==>> as TradeLoanService.TradeLoanApplication.CloseFacilityPaidOffController
    rectangle "==Loan Facility Restructuring Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.LoanFacilityRestructuringCommandHandler
    rectangle "==Irregular Progressive Disbursement Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.IrregularProgressiveDisbursementCommandHandler
    rectangle "==Compensate Irregular Disbursement Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcixDb21wZW5zYXRpb24=>> as TradeLoanService.TradeLoanApplication.CompensateIrregularDisbursementCommandHandler
    rectangle "==Plan Equal Installment Schedule Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.PlanEqualInstallmentScheduleCommandHandler
    rectangle "==Regular Disbursement Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.RegularDisbursementCommandHandler
    rectangle "==Reject Facility Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.RejectFacilityCommandHandler
    rectangle "==Define Loan Type Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.DefineLoanTypeCommandHandler
    rectangle "==Submit Facility For Approval Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.SubmitFacilityForApprovalCommandHandler
    rectangle "==Compensate Approval Submission Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcixDb21wZW5zYXRpb24=>> as TradeLoanService.TradeLoanApplication.CompensateApprovalSubmissionCommandHandler
    rectangle "==Update Facility Collateral Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.UpdateFacilityCollateralCommandHandler
    rectangle "==Cancel Facility Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.CancelFacilityCommandHandler
    rectangle "==Approve Facility Command Handler\n<size:16>[Component: Command Handler]</size>" <<Element-RWxlbWVudCxDb21wb25lbnQsSGFuZGxlcg==>> as TradeLoanService.TradeLoanApplication.ApproveFacilityCommandHandler
  }

}

@enduml