graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Trade Loan Service - Trade Loan Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 11 ["Trade Loan Application"]
      style 11 fill:#ffffff,stroke:#2e6295,color:#2e6295

      50["<div style='font-weight: bold'>DevAuthCallbackController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/dev/auth</div>"]
      style 50 fill:#7cb342,stroke:#567d2e,color:#ffffff
      51["<div style='font-weight: bold'>AddFacilityCollateralController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/collaterals</div>"]
      style 51 fill:#7cb342,stroke:#567d2e,color:#ffffff
      52["<div style='font-weight: bold'>ApproveFacilityController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/approve</div>"]
      style 52 fill:#7cb342,stroke:#567d2e,color:#ffffff
      53["<div style='font-weight: bold'>CancelFacilityController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/cancel</div>"]
      style 53 fill:#7cb342,stroke:#567d2e,color:#ffffff
      54["<div style='font-weight: bold'>CloseFacilityDefaultedController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/close-defaulted</div>"]
      style 54 fill:#7cb342,stroke:#567d2e,color:#ffffff
      55["<div style='font-weight: bold'>CloseFacilityPaidOffController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/close-paid-off</div>"]
      style 55 fill:#7cb342,stroke:#567d2e,color:#ffffff
      56["<div style='font-weight: bold'>DefineLoanArrangementController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/loan-arrangements/define</div>"]
      style 56 fill:#7cb342,stroke:#567d2e,color:#ffffff
      57["<div style='font-weight: bold'>DefineLoanTypeController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/loan-types/define</div>"]
      style 57 fill:#7cb342,stroke:#567d2e,color:#ffffff
      58["<div style='font-weight: bold'>FullLoanFacilityLifecycleController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/full-lifecycle</div>"]
      style 58 fill:#7cb342,stroke:#567d2e,color:#ffffff
      59["<div style='font-weight: bold'>IrregularProgressiveDisbursementController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/disburse/progressive-irregular</div>"]
      style 59 fill:#7cb342,stroke:#567d2e,color:#ffffff
      60["<div style='font-weight: bold'>IssueFacilityContractController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/issue-contract</div>"]
      style 60 fill:#7cb342,stroke:#567d2e,color:#ffffff
      61["<div style='font-weight: bold'>LumpSumDisbursementController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/disburse/lump-sum</div>"]
      style 61 fill:#7cb342,stroke:#567d2e,color:#ffffff
      62["<div style='font-weight: bold'>OpenFacilityCaseController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/open-case</div>"]
      style 62 fill:#7cb342,stroke:#567d2e,color:#ffffff
      63["<div style='font-weight: bold'>RegularDisbursementController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/disburse/regular</div>"]
      style 63 fill:#7cb342,stroke:#567d2e,color:#ffffff
      64["<div style='font-weight: bold'>RejectFacilityController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/reject</div>"]
      style 64 fill:#7cb342,stroke:#567d2e,color:#ffffff
      65["<div style='font-weight: bold'>SubmitFacilityForApprovalController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/facilities/{facilityId}/submit-for-approval</div>"]
      style 65 fill:#7cb342,stroke:#567d2e,color:#ffffff
      72["<div style='font-weight: bold'>AddFacilityCollateralCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles add facility<br />collateral</div>"]
      style 72 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      73["<div style='font-weight: bold'>CompensateCollateralCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate collateral</div>"]
      style 73 fill:#ef5350,stroke:#a73a38,color:#ffffff
      74["<div style='font-weight: bold'>ApproveFacilityCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles approve facility</div>"]
      style 74 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      75["<div style='font-weight: bold'>CompensateApprovalCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate approval</div>"]
      style 75 fill:#ef5350,stroke:#a73a38,color:#ffffff
      76["<div style='font-weight: bold'>CancelFacilityCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles cancel facility</div>"]
      style 76 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      77["<div style='font-weight: bold'>CloseFacilityDefaultedCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles close facility<br />defaulted</div>"]
      style 77 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      78["<div style='font-weight: bold'>CloseFacilityPaidOffCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles close facility paid<br />off</div>"]
      style 78 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      79["<div style='font-weight: bold'>CollectInstallmentCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles collect installment</div>"]
      style 79 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      80["<div style='font-weight: bold'>DefineTradeLoanArrangementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles define trade loan<br />arrangement</div>"]
      style 80 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      81["<div style='font-weight: bold'>DefineLoanTypeCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles define loan type</div>"]
      style 81 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      82["<div style='font-weight: bold'>FullLoanFacilityLifecycleCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles full loan facility<br />lifecycle</div>"]
      style 82 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      83["<div style='font-weight: bold'>FullLifecycleRevertCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles full lifecycle revert</div>"]
      style 83 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      84["<div style='font-weight: bold'>IrregularProgressiveDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles irregular progressive<br />disbursement</div>"]
      style 84 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      85["<div style='font-weight: bold'>CompensateIrregularDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate irregular<br />disbursement</div>"]
      style 85 fill:#ef5350,stroke:#a73a38,color:#ffffff
    end

  end