graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Trade Loan Service - Trade Loan Application"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 6 ["Trade Loan Service"]
      style 6 fill:#ffffff,stroke:#0b4884,color:#0b4884

      subgraph 7 ["Trade Loan Application"]
        style 7 fill:#ffffff,stroke:#2e6295,color:#2e6295

        27["<div style='font-weight: bold'>Reconciliation By Application Number Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 27 fill:#7cb342,stroke:#567d2e,color:#ffffff
        28["<div style='font-weight: bold'>Dev Auth Callback Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 28 fill:#7cb342,stroke:#567d2e,color:#ffffff
        33["<div style='font-weight: bold'>Approve Facility Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 33 fill:#7cb342,stroke:#567d2e,color:#ffffff
        34["<div style='font-weight: bold'>Issue Facility Contract Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 34 fill:#7cb342,stroke:#567d2e,color:#ffffff
        35["<div style='font-weight: bold'>Add Facility Collateral Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 35 fill:#7cb342,stroke:#567d2e,color:#ffffff
        36["<div style='font-weight: bold'>Define Loan Arrangement Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 36 fill:#7cb342,stroke:#567d2e,color:#ffffff
        37["<div style='font-weight: bold'>Lump Sum Disbursement Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 37 fill:#7cb342,stroke:#567d2e,color:#ffffff
        38["<div style='font-weight: bold'>Define Loan Type Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 38 fill:#7cb342,stroke:#567d2e,color:#ffffff
        39["<div style='font-weight: bold'>Submit Facility For Approval Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 39 fill:#7cb342,stroke:#567d2e,color:#ffffff
        40["<div style='font-weight: bold'>Reject Facility Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 40 fill:#7cb342,stroke:#567d2e,color:#ffffff
        41["<div style='font-weight: bold'>Open Facility Case Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 41 fill:#7cb342,stroke:#567d2e,color:#ffffff
        42["<div style='font-weight: bold'>Irregular Progressive Disbursement Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 42 fill:#7cb342,stroke:#567d2e,color:#ffffff
        43["<div style='font-weight: bold'>Close Facility Defaulted Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 43 fill:#7cb342,stroke:#567d2e,color:#ffffff
        44["<div style='font-weight: bold'>Close Facility Paid Off Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring MVC Controller]</div>"]
        style 44 fill:#7cb342,stroke:#567d2e,color:#ffffff
        45["<div style='font-weight: bold'>Loan Facility Restructuring Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 45 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        46["<div style='font-weight: bold'>Irregular Progressive Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 46 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        47["<div style='font-weight: bold'>Compensate Irregular Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 47 fill:#ef5350,stroke:#a73a38,color:#ffffff
        48["<div style='font-weight: bold'>Plan Equal Installment Schedule Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 48 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        49["<div style='font-weight: bold'>Regular Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 49 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        50["<div style='font-weight: bold'>Reject Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 50 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        51["<div style='font-weight: bold'>Define Loan Type Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 51 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        52["<div style='font-weight: bold'>Submit Facility For Approval Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 52 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        53["<div style='font-weight: bold'>Compensate Approval Submission Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 53 fill:#ef5350,stroke:#a73a38,color:#ffffff
        54["<div style='font-weight: bold'>Update Facility Collateral Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 54 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        55["<div style='font-weight: bold'>Cancel Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 55 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        56["<div style='font-weight: bold'>Approve Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 56 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        57["<div style='font-weight: bold'>Compensate Approval Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 57 fill:#ef5350,stroke:#a73a38,color:#ffffff
        58["<div style='font-weight: bold'>Originate Loan Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 58 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        59["<div style='font-weight: bold'>Compensate Origination Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 59 fill:#ef5350,stroke:#a73a38,color:#ffffff
        60["<div style='font-weight: bold'>Close Facility Defaulted Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 60 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      end

    end

  end