graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Trade Loan Service - Trade Loan Application"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 6 ["Trade Loan Service"]
      style 6 fill:#ffffff,stroke:#0b4884,color:#0b4884

      subgraph 7 ["Trade Loan Application"]
        style 7 fill:#ffffff,stroke:#2e6295,color:#2e6295

        57["<div style='font-weight: bold'>Compensate Approval Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 57 fill:#ef5350,stroke:#a73a38,color:#ffffff
        58["<div style='font-weight: bold'>Originate Loan Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 58 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        59["<div style='font-weight: bold'>Compensate Origination Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 59 fill:#ef5350,stroke:#a73a38,color:#ffffff
        60["<div style='font-weight: bold'>Close Facility Defaulted Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 60 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        61["<div style='font-weight: bold'>Close Facility Paid Off Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 61 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        62["<div style='font-weight: bold'>Compensate Close Facility Paid Off Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 62 fill:#ef5350,stroke:#a73a38,color:#ffffff
        63["<div style='font-weight: bold'>Issue Facility Contract Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 63 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        64["<div style='font-weight: bold'>Compensate Contract Issuance Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 64 fill:#ef5350,stroke:#a73a38,color:#ffffff
        65["<div style='font-weight: bold'>Define Trade Loan Arrangement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 65 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        66["<div style='font-weight: bold'>Lump Sum Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 66 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        67["<div style='font-weight: bold'>Compensate Lump Sum Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 67 fill:#ef5350,stroke:#a73a38,color:#ffffff
        68["<div style='font-weight: bold'>Add Facility Collateral Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 68 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        69["<div style='font-weight: bold'>Compensate Collateral Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 69 fill:#ef5350,stroke:#a73a38,color:#ffffff
        70["<div style='font-weight: bold'>Collect Installment Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 70 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        71["<div style='font-weight: bold'>Compensate Collect Installment Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 71 fill:#ef5350,stroke:#a73a38,color:#ffffff
        72["<div style='font-weight: bold'>Get Loan Arrangement By Code Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 72 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        73["<div style='font-weight: bold'>Loan Type Arrangement Filter Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 73 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        74["<div style='font-weight: bold'>Get Loan Arrangement By Id Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 74 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        75["<div style='font-weight: bold'>Find All Loan Arrangements Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 75 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        76["<div style='font-weight: bold'>Get Installment Schedule By Id Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 76 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        77["<div style='font-weight: bold'>Find All Loan Types Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 77 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        78["<div style='font-weight: bold'>Get Loan Type By Id Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 78 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        79["<div style='font-weight: bold'>Loan Type Filter Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 79 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        80["<div style='font-weight: bold'>Get Loan Type By Code Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 80 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        81["<div style='font-weight: bold'>Get Facility By Id Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 81 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        82["<div style='font-weight: bold'>Get Facility By Application Number Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 82 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        83["<div style='font-weight: bold'>Find All Loan Facilities Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 83 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        84["<div style='font-weight: bold'>Resolve Facility Id By Application Number Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 84 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        85["<div style='font-weight: bold'>Search Loan Facilities Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 85 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        86[("<div style='font-weight: bold'>Trade Loan Arrangement Repository Adapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div>")]
        style 86 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      end

    end

  end