graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Trade Loan Service - Trade Loan Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 11 ["Trade Loan Application"]
      style 11 fill:#ffffff,stroke:#2e6295,color:#2e6295

      110["<div style='font-weight: bold'>TradeLoanFacilityEventFactory</div><div style='font-size: 70%; margin-top: 0px'>[Component: DDD Entity]</div><div style='font-size: 80%; margin-top:10px'>trade loan facility event<br />factory entity</div>"]
      style 110 fill:#ffb74d,stroke:#b28035,color:#000000
      111["<div style='font-weight: bold'>TradeSanctionedLoan</div><div style='font-size: 70%; margin-top: 0px'>[Component: DDD Aggregate Root]</div><div style='font-size: 80%; margin-top:10px'>trade sanctioned loan<br />aggregate</div>"]
      style 111 fill:#ff9800,stroke:#b26a00,color:#000000
      112["<div style='font-weight: bold'>TradeLoanType</div><div style='font-size: 70%; margin-top: 0px'>[Component: DDD Aggregate Root]</div><div style='font-size: 80%; margin-top:10px'>trade loan type aggregate</div>"]
      style 112 fill:#ff9800,stroke:#b26a00,color:#000000
      113["<div style='font-weight: bold'>TradeRepaymentSchedulingService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade repayment scheduling<br />service domain service</div>"]
      style 113 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      114["<div style='font-weight: bold'>TradeInterestCalculationService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade interest calculation<br />service domain service</div>"]
      style 114 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      115["<div style='font-weight: bold'>TradeLoanFacilityService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade loan facility service<br />domain service</div>"]
      style 115 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      116["<div style='font-weight: bold'>IrregularProgressiveDisbursementTransactionService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>irregular progressive<br />disbursement transaction<br />service domain service</div>"]
      style 116 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      117["<div style='font-weight: bold'>TradeIssueContractTransactionService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade issue contract<br />transaction service domain<br />service</div>"]
      style 117 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      118["<div style='font-weight: bold'>TradeLampSunDisbursementTransactionService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade lamp sun disbursement<br />transaction service domain<br />service</div>"]
      style 118 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      119["<div style='font-weight: bold'>TradeLoanFacilityValidationService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade loan facility<br />validation service domain<br />service</div>"]
      style 119 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      120["<div style='font-weight: bold'>TradeSanctionValidationService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade sanction validation<br />service domain service</div>"]
      style 120 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      121["<div style='font-weight: bold'>TradeLoanTypeValidationService</div><div style='font-size: 70%; margin-top: 0px'>[Component: Domain Service]</div><div style='font-size: 80%; margin-top:10px'>trade loan type validation<br />service domain service</div>"]
      style 121 fill:#29b6f6,stroke:#1c7fac,color:#ffffff
      122[("<div style='font-weight: bold'>InstallmentScheduleRepositoryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>InstallmentSchedule<br />persistence adapter</div>")]
      style 122 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      123[("<div style='font-weight: bold'>TradeLoanArrangementRepositoryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanArrangement<br />persistence adapter</div>")]
      style 123 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      124[("<div style='font-weight: bold'>TradeLoanFacilityRepositoryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanFacility persistence<br />adapter</div>")]
      style 124 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      125[("<div style='font-weight: bold'>TradeLoanTypeRepositoryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanType persistence<br />adapter</div>")]
      style 125 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      126[("<div style='font-weight: bold'>JpaTradeInstallmentScheduleQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeInstallmentSchedule<br />query adapter</div>")]
      style 126 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      127[("<div style='font-weight: bold'>JpaTradeLoanArrangementQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanArrangement query<br />adapter</div>")]
      style 127 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      128[("<div style='font-weight: bold'>JpaFacilityQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>Facility query adapter</div>")]
      style 128 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      129[("<div style='font-weight: bold'>JpaTradeLoanTypeQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanType query adapter</div>")]
      style 129 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      130["<div style='font-weight: bold'>AccountServiceAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>account service client</div>"]
      style 130 fill:#ec407a,stroke:#a52c55,color:#ffffff
      131["<div style='font-weight: bold'>CollateralAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>collateral client</div>"]
      style 131 fill:#ec407a,stroke:#a52c55,color:#ffffff
      132["<div style='font-weight: bold'>CustomerServiceAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>customer service client</div>"]
      style 132 fill:#ec407a,stroke:#a52c55,color:#ffffff
      133["<div style='font-weight: bold'>DepositServiceAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>deposit service client</div>"]
      style 133 fill:#ec407a,stroke:#a52c55,color:#ffffff
      134["<div style='font-weight: bold'>FcbServiceImpl</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>fcb client</div>"]
      style 134 fill:#ec407a,stroke:#a52c55,color:#ffffff
      135["<div style='font-weight: bold'>LoanServiceAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>loan service client</div>"]
      style 135 fill:#ec407a,stroke:#a52c55,color:#ffffff
      136["<div style='font-weight: bold'>TransactionPostingAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring WebClient]</div><div style='font-size: 80%; margin-top:10px'>transaction posting client</div>"]
      style 136 fill:#ec407a,stroke:#a52c55,color:#ffffff
      137["<div style='font-weight: bold'>InstallmentScheduleOutboxHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Pattern]</div><div style='font-size: 80%; margin-top:10px'>InstallmentSchedule outbox<br />handler</div>"]
      style 137 fill:#66bb6a,stroke:#47824a,color:#000000
      138["<div style='font-weight: bold'>TradeLoanArrangementOutboxHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Pattern]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanArrangement outbox<br />handler</div>"]
      style 138 fill:#66bb6a,stroke:#47824a,color:#000000
      139["<div style='font-weight: bold'>TradeLoanFacilityOutboxHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Pattern]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanFacility outbox<br />handler</div>"]
      style 139 fill:#66bb6a,stroke:#47824a,color:#000000
    end

    118-. "<div>Uses</div><div style='font-size: 70%'></div>" .->114
  end