graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Trade Loan Service - Trade Loan Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 11 ["Trade Loan Application"]
      style 11 fill:#ffffff,stroke:#2e6295,color:#2e6295

      100["<div style='font-weight: bold'>GetLoanArrangementByIdQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles get loan arrangement<br />by id queries</div>"]
      style 100 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      71["<div style='font-weight: bold'>AddFacilityCollateralCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles add facility<br />collateral</div>"]
      style 71 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      72["<div style='font-weight: bold'>CompensateCollateralCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate collateral</div>"]
      style 72 fill:#ef5350,stroke:#a73a38,color:#ffffff
      73["<div style='font-weight: bold'>ApproveFacilityCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles approve facility</div>"]
      style 73 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      74["<div style='font-weight: bold'>CompensateApprovalCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate approval</div>"]
      style 74 fill:#ef5350,stroke:#a73a38,color:#ffffff
      75["<div style='font-weight: bold'>CancelFacilityCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles cancel facility</div>"]
      style 75 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      76["<div style='font-weight: bold'>CloseFacilityDefaultedCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles close facility<br />defaulted</div>"]
      style 76 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      77["<div style='font-weight: bold'>CloseFacilityPaidOffCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles close facility paid<br />off</div>"]
      style 77 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      78["<div style='font-weight: bold'>CompensateCloseFacilityPaidOffCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate close<br />facility paid off</div>"]
      style 78 fill:#ef5350,stroke:#a73a38,color:#ffffff
      79["<div style='font-weight: bold'>CollectInstallmentCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles collect installment</div>"]
      style 79 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      80["<div style='font-weight: bold'>CompensateCollectInstallmentCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate collect<br />installment</div>"]
      style 80 fill:#ef5350,stroke:#a73a38,color:#ffffff
      81["<div style='font-weight: bold'>DefineTradeLoanArrangementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles define trade loan<br />arrangement</div>"]
      style 81 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      82["<div style='font-weight: bold'>DefineLoanTypeCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles define loan type</div>"]
      style 82 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      83["<div style='font-weight: bold'>FullLoanFacilityLifecycleCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles full loan facility<br />lifecycle</div>"]
      style 83 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      84["<div style='font-weight: bold'>FullLifecycleRevertCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles full lifecycle revert</div>"]
      style 84 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      85["<div style='font-weight: bold'>IrregularProgressiveDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles irregular progressive<br />disbursement</div>"]
      style 85 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      86["<div style='font-weight: bold'>CompensateIrregularDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate irregular<br />disbursement</div>"]
      style 86 fill:#ef5350,stroke:#a73a38,color:#ffffff
      87["<div style='font-weight: bold'>IssueFacilityContractCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles issue facility<br />contract</div>"]
      style 87 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      88["<div style='font-weight: bold'>CompensateContractIssuanceCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate contract<br />issuance</div>"]
      style 88 fill:#ef5350,stroke:#a73a38,color:#ffffff
      89["<div style='font-weight: bold'>LumpSumDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles lump sum disbursement</div>"]
      style 89 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      90["<div style='font-weight: bold'>CompensateLumpSumDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate lump sum<br />disbursement</div>"]
      style 90 fill:#ef5350,stroke:#a73a38,color:#ffffff
      91["<div style='font-weight: bold'>OriginateLoanFacilityCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles originate loan<br />facility</div>"]
      style 91 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      92["<div style='font-weight: bold'>CompensateOriginationCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate<br />origination</div>"]
      style 92 fill:#ef5350,stroke:#a73a38,color:#ffffff
      93["<div style='font-weight: bold'>PlanEqualInstallmentScheduleCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles plan equal<br />installment schedule</div>"]
      style 93 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      94["<div style='font-weight: bold'>RegularDisbursementCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles regular disbursement</div>"]
      style 94 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      95["<div style='font-weight: bold'>RejectFacilityCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles reject facility</div>"]
      style 95 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      96["<div style='font-weight: bold'>SubmitFacilityForApprovalCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles submit facility for<br />approval</div>"]
      style 96 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      97["<div style='font-weight: bold'>CompensateApprovalSubmissionCommandHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles compensate approval<br />submission</div>"]
      style 97 fill:#ef5350,stroke:#a73a38,color:#ffffff
      98["<div style='font-weight: bold'>GetInstallmentScheduleByIdQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles get installment<br />schedule by id queries</div>"]
      style 98 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      99["<div style='font-weight: bold'>FindAllLoanArrangementsQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles find all loan<br />arrangements queries</div>"]
      style 99 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
    end

  end