graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Trade Loan Service - Trade Loan Application"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 6 ["Trade Loan Service"]
      style 6 fill:#ffffff,stroke:#0b4884,color:#0b4884

      subgraph 7 ["Trade Loan Application"]
        style 7 fill:#ffffff,stroke:#2e6295,color:#2e6295

        45["<div style='font-weight: bold'>Loan Facility Restructuring Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 45 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        46["<div style='font-weight: bold'>Irregular Progressive Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 46 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        47["<div style='font-weight: bold'>Compensate Irregular Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 47 fill:#ef5350,stroke:#a73a38,color:#ffffff
        48["<div style='font-weight: bold'>Plan Equal Installment Schedule Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 48 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        49["<div style='font-weight: bold'>Regular Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 49 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        50["<div style='font-weight: bold'>Reject Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 50 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        51["<div style='font-weight: bold'>Define Loan Type Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 51 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        52["<div style='font-weight: bold'>Submit Facility For Approval Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 52 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        53["<div style='font-weight: bold'>Compensate Approval Submission Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 53 fill:#ef5350,stroke:#a73a38,color:#ffffff
        54["<div style='font-weight: bold'>Update Facility Collateral Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 54 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        55["<div style='font-weight: bold'>Cancel Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 55 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        56["<div style='font-weight: bold'>Approve Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 56 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        57["<div style='font-weight: bold'>Compensate Approval Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 57 fill:#ef5350,stroke:#a73a38,color:#ffffff
        58["<div style='font-weight: bold'>Originate Loan Facility Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 58 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        59["<div style='font-weight: bold'>Compensate Origination Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 59 fill:#ef5350,stroke:#a73a38,color:#ffffff
        60["<div style='font-weight: bold'>Close Facility Defaulted Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 60 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        61["<div style='font-weight: bold'>Close Facility Paid Off Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 61 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        62["<div style='font-weight: bold'>Compensate Close Facility Paid Off Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 62 fill:#ef5350,stroke:#a73a38,color:#ffffff
        63["<div style='font-weight: bold'>Issue Facility Contract Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 63 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        64["<div style='font-weight: bold'>Compensate Contract Issuance Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 64 fill:#ef5350,stroke:#a73a38,color:#ffffff
        65["<div style='font-weight: bold'>Define Trade Loan Arrangement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 65 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        66["<div style='font-weight: bold'>Lump Sum Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 66 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        67["<div style='font-weight: bold'>Compensate Lump Sum Disbursement Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 67 fill:#ef5350,stroke:#a73a38,color:#ffffff
        68["<div style='font-weight: bold'>Add Facility Collateral Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 68 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        69["<div style='font-weight: bold'>Compensate Collateral Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 69 fill:#ef5350,stroke:#a73a38,color:#ffffff
        70["<div style='font-weight: bold'>Collect Installment Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 70 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        71["<div style='font-weight: bold'>Compensate Collect Installment Command Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Command Handler]</div>"]
        style 71 fill:#ef5350,stroke:#a73a38,color:#ffffff
        72["<div style='font-weight: bold'>Get Loan Arrangement By Code Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 72 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        73["<div style='font-weight: bold'>Loan Type Arrangement Filter Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 73 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
        74["<div style='font-weight: bold'>Get Loan Arrangement By Id Query Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div>"]
        style 74 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      end

    end

    63-. "<div>Compensates on failure</div><div style='font-size: 70%'></div>" .->64
    66-. "<div>Compensates on failure</div><div style='font-size: 70%'></div>" .->67
    46-. "<div>Compensates on failure</div><div style='font-size: 70%'></div>" .->47

  end