graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Trade Loan Service - Trade Loan Application"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 6 ["Trade Loan Service"]
      style 6 fill:#ffffff,stroke:#0b4884,color:#0b4884

      subgraph 7 ["Trade Loan Application"]
        style 7 fill:#ffffff,stroke:#2e6295,color:#2e6295

        100["<div style='font-weight: bold'>Loan Facility Mcp Tools</div><div style='font-size: 70%; margin-top: 0px'>[Component: MCP Tool]</div>"]
        style 100 fill:#26a69a,stroke:#1a746b,color:#ffffff
        101["<div style='font-weight: bold'>Loan Type Mcp Tools</div><div style='font-size: 70%; margin-top: 0px'>[Component: MCP Tool]</div>"]
        style 101 fill:#26a69a,stroke:#1a746b,color:#ffffff
        102["<div style='font-weight: bold'>Loan Arrangement Mcp Tools</div><div style='font-size: 70%; margin-top: 0px'>[Component: MCP Tool]</div>"]
        style 102 fill:#26a69a,stroke:#1a746b,color:#ffffff
        103["<div style='font-weight: bold'>Installment Schedule Mcp Tools</div><div style='font-size: 70%; margin-top: 0px'>[Component: MCP Tool]</div>"]
        style 103 fill:#26a69a,stroke:#1a746b,color:#ffffff
        99["<div style='font-weight: bold'>Reconciliation Ops Mcp Tools</div><div style='font-size: 70%; margin-top: 0px'>[Component: MCP Tool]</div>"]
        style 99 fill:#26a69a,stroke:#1a746b,color:#ffffff
      end

    end

  end