graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Trade Loan Service - Trade Loan Application"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 6 ["Trade Loan Service"]
      style 6 fill:#ffffff,stroke:#0b4884,color:#0b4884

      subgraph 7 ["Trade Loan Application"]
        style 7 fill:#ffffff,stroke:#2e6295,color:#2e6295

        94["<div style='font-weight: bold'>Trade Loan Arrangement Outbox Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Publisher]</div>"]
        style 94 fill:#66bb6a,stroke:#47824a,color:#000000
        95["<div style='font-weight: bold'>Installment Schedule Outbox Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Publisher]</div>"]
        style 95 fill:#66bb6a,stroke:#47824a,color:#000000
        96["<div style='font-weight: bold'>Trade Loan Type Outbox Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Publisher]</div>"]
        style 96 fill:#66bb6a,stroke:#47824a,color:#000000
        97["<div style='font-weight: bold'>Trade Loan Facility Outbox Handler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Outbox Publisher]</div>"]
        style 97 fill:#66bb6a,stroke:#47824a,color:#000000
        98["<div style='font-weight: bold'>Fcb Event Consumer</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Kafka Listener]</div>"]
        style 98 fill:#ff7043,stroke:#b24e2e,color:#ffffff
      end

      11["<div style='font-weight: bold'>ActiveMQ Artemis</div><div style='font-size: 70%; margin-top: 0px'>[Container: ActiveMQ Artemis 2.43 (Jakarta JMS)]</div><div style='font-size: 80%; margin-top:10px'>Primary FCB request/reply<br />corridor broker</div>"]
      style 11 fill:#f5a623,stroke:#ab7418,color:#000000
      9["<div style='font-weight: bold'>Kafka</div><div style='font-size: 70%; margin-top: 0px'>[Container: Apache Kafka (SASL_PLAINTEXT/SCRAM-SHA-256)]</div><div style='font-size: 80%; margin-top:10px'>Event streaming +<br />request/reply fallback<br />transport</div>"]
      style 9 fill:#f5a623,stroke:#ab7418,color:#000000
    end

    94-. "<div>Publishes events</div><div style='font-size: 70%'>[Kafka (SASL/SCRAM)]</div>" .->9
    95-. "<div>Publishes events</div><div style='font-size: 70%'>[Kafka (SASL/SCRAM)]</div>" .->9
    96-. "<div>Publishes events</div><div style='font-size: 70%'>[Kafka (SASL/SCRAM)]</div>" .->9
    97-. "<div>Publishes events</div><div style='font-size: 70%'>[Kafka (SASL/SCRAM)]</div>" .->9
    98-. "<div>Consumes from</div><div style='font-size: 70%'>[Kafka (SASL/SCRAM)]</div>" .->9

  end