graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Trade Loan Service - Trade Loan Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 11 ["Trade Loan Application"]
      style 11 fill:#ffffff,stroke:#2e6295,color:#2e6295

      100["<div style='font-weight: bold'>GetLoanArrangementByIdQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles get loan arrangement<br />by id queries</div>"]
      style 100 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      101["<div style='font-weight: bold'>LoanTypeArrangementFilterQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles loan type arrangement<br />filter queries</div>"]
      style 101 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      102["<div style='font-weight: bold'>FindAllLoanFacilitiesQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles find all loan<br />facilities queries</div>"]
      style 102 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      103["<div style='font-weight: bold'>GetFacilityByIdQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles get facility by id<br />queries</div>"]
      style 103 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      104["<div style='font-weight: bold'>SearchLoanFacilitiesQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles search loan<br />facilities queries</div>"]
      style 104 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      105["<div style='font-weight: bold'>FindAllLoanTypesQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles find all loan types<br />queries</div>"]
      style 105 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      106["<div style='font-weight: bold'>GetLoanTypeByIdQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles get loan type by id<br />queries</div>"]
      style 106 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      107["<div style='font-weight: bold'>LoanTypeFilterQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles loan type filter<br />queries</div>"]
      style 107 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      125[("<div style='font-weight: bold'>JpaTradeInstallmentScheduleQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeInstallmentSchedule<br />query adapter</div>")]
      style 125 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      126[("<div style='font-weight: bold'>JpaTradeLoanArrangementQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanArrangement query<br />adapter</div>")]
      style 126 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      127[("<div style='font-weight: bold'>JpaFacilityQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>Facility query adapter</div>")]
      style 127 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      128[("<div style='font-weight: bold'>JpaTradeLoanTypeQueryAdapter</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Data JPA]</div><div style='font-size: 80%; margin-top:10px'>TradeLoanType query adapter</div>")]
      style 128 fill:#5c6bc0,stroke:#404a86,color:#ffffff
      65["<div style='font-weight: bold'>InstallmentScheduleQueryController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/installment-schedules</div>"]
      style 65 fill:#7cb342,stroke:#567d2e,color:#ffffff
      66["<div style='font-weight: bold'>LoanArrangementQueryController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/loan-arrangements</div>"]
      style 66 fill:#7cb342,stroke:#567d2e,color:#ffffff
      67["<div style='font-weight: bold'>FacilityQueryController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/loan-facilities</div>"]
      style 67 fill:#7cb342,stroke:#567d2e,color:#ffffff
      68["<div style='font-weight: bold'>LoanTypeQueryController</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring REST Controller]</div><div style='font-size: 80%; margin-top:10px'>REST API:<br />/api/{version}/loan-types</div>"]
      style 68 fill:#7cb342,stroke:#567d2e,color:#ffffff
      98["<div style='font-weight: bold'>GetInstallmentScheduleByIdQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles get installment<br />schedule by id queries</div>"]
      style 98 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
      99["<div style='font-weight: bold'>FindAllLoanArrangementsQueryHandler</div><div style='font-size: 70%; margin-top: 0px'>[Component: Query Handler]</div><div style='font-size: 80%; margin-top:10px'>Handles find all loan<br />arrangements queries</div>"]
      style 99 fill:#42a5f5,stroke:#2e73ab,color:#ffffff
    end

  end